import type { Edge } from '@xyflow/react';
import type { TableNode, ColumnDef, SqlDialect, Result, FkRelationship } from '../types/schema.types';

export function resolveFkRelationship(
  nodes: TableNode[],
  edge: Edge
): FkRelationship | null {
  const nodeA = nodes.find((n) => n.id === edge.source);
  const nodeB = nodes.find((n) => n.id === edge.target);

  if (!nodeA || !nodeB) return null;

  const colA = nodeA.data.columns.find((c) => c.id === edge.sourceHandle);
  const colB = nodeB.data.columns.find((c) => c.id === edge.targetHandle);

  if (!colA || !colB) return null;

  // Determine parent (PK provider) vs child (FK owner)
  if (!colA.isPrimary && colB.isPrimary) {
    return { parentNode: nodeB, parentCol: colB, childNode: nodeA, childCol: colA };
  }

  return { parentNode: nodeA, parentCol: colA, childNode: nodeB, childCol: colB };
}

export function generateSql(
  nodes: TableNode[],
  edges: Edge[],
  dialect: SqlDialect = 'postgresql'
): Result<string> {
  try {
    let sql = `-- Generated by DevToolsPro SQL Schema Designer (${dialect.toUpperCase()})\n\n`;
    const q = dialect === 'mysql' ? '`' : '"';

    nodes.forEach((node) => {
      const { tableName, columns } = node.data;
      if (!tableName) return;

      sql += `CREATE TABLE ${q}${tableName}${q} (\n`;

      const colStrings: string[] = columns.map((col) => {
        const colName = col.name ? col.name.trim() : 'untitled';
        const colType = col.type ? col.type.trim() : 'VARCHAR(255)';

        let line = `  ${q}${colName}${q} ${colType}`;

        if (col.isPrimary) {
          if (dialect === 'sqlite' && colType.toUpperCase() === 'SERIAL') {
            line = `  ${q}${colName}${q} INTEGER PRIMARY KEY AUTOINCREMENT`;
          } else if (dialect === 'mysql' && colType.toUpperCase() === 'SERIAL') {
            line = `  ${q}${colName}${q} BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`;
          } else {
            line += ' PRIMARY KEY';
          }
        }

        if (!col.isNullable && !col.isPrimary) {
          line += ' NOT NULL';
        }

        if (col.isUnique && !col.isPrimary) {
          line += ' UNIQUE';
        }

        if (col.defaultValue && col.defaultValue.trim()) {
          line += ` DEFAULT ${col.defaultValue.trim()}`;
        }

        return line;
      });

      // For SQLite, generate inline Foreign Keys inside CREATE TABLE
      if (dialect === 'sqlite') {
        edges.forEach((edge) => {
          const rel = resolveFkRelationship(nodes, edge);
          if (rel && rel.childNode.id === node.id) {
            colStrings.push(
              `  FOREIGN KEY (${q}${rel.childCol.name}${q}) REFERENCES ${q}${rel.parentNode.data.tableName}${q} (${q}${rel.parentCol.name}${q}) ON DELETE CASCADE`
            );
          }
        });
      }

      sql += colStrings.join(',\n');
      sql += '\n);\n\n';
    });

    // Foreign keys for PostgreSQL and MySQL
    if (edges.length > 0 && dialect !== 'sqlite') {
      let fkSql = '';
      edges.forEach((edge) => {
        const rel = resolveFkRelationship(nodes, edge);
        if (!rel) return;

        const fkName = `fk_${rel.childNode.data.tableName}_${rel.childCol.name}`;

        fkSql += `ALTER TABLE ${q}${rel.childNode.data.tableName}${q}\n`;
        fkSql += `  ADD CONSTRAINT ${q}${fkName}${q}\n`;
        fkSql += `  FOREIGN KEY (${q}${rel.childCol.name}${q})\n`;
        fkSql += `  REFERENCES ${q}${rel.parentNode.data.tableName}${q} (${q}${rel.parentCol.name}${q})\n`;
        fkSql += `  ON DELETE CASCADE ON UPDATE CASCADE;\n\n`;
      });

      if (fkSql) {
        sql += '-- Foreign Key Constraints\n' + fkSql;
      }
    }

    return { success: true, data: sql.trim() };
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Failed to generate SQL.';
    return { success: false, error: msg };
  }
}
