import { Node, Edge } from '@xyflow/react';

export interface ColumnDef {
  id: string;
  name: string;
  type: string;
  isPrimary: boolean;
  isNullable: boolean;
  isUnique?: boolean;
  defaultValue?: string;
}

export interface TableNodeData extends Record<string, unknown> {
  tableName: string;
  columns: ColumnDef[];
}

export type TableNode = Node<TableNodeData>;

export type Result<T> = { success: true; data: T } | { success: false; error: string };

export type SqlDialect = 'postgresql' | 'mysql' | 'sqlite';
export type ExportFormat = 'sql' | 'prisma' | 'typescript' | 'mermaid';

export const DIALECT_DATATYPES: Record<SqlDialect, { category: string; types: string[] }[]> = {
  postgresql: [
    { category: 'Numeric', types: ['SERIAL', 'BIGSERIAL', 'SMALLINT', 'INTEGER', 'BIGINT', 'DECIMAL(10,2)', 'NUMERIC', 'REAL', 'DOUBLE PRECISION'] },
    { category: 'String / Text', types: ['VARCHAR(255)', 'CHAR(1)', 'TEXT', 'CITEXT', 'UUID'] },
    { category: 'Date / Time', types: ['TIMESTAMP', 'TIMESTAMPTZ', 'DATE', 'TIME', 'TIMETZ', 'INTERVAL'] },
    { category: 'Boolean', types: ['BOOLEAN'] },
    { category: 'JSON / Objects', types: ['JSONB', 'JSON'] },
    { category: 'Binary & Network', types: ['BYTEA', 'INET', 'CIDR', 'MACADDR'] },
  ],
  mysql: [
    { category: 'Numeric', types: ['INT', 'BIGINT', 'MEDIUMINT', 'SMALLINT', 'TINYINT', 'DECIMAL(10,2)', 'FLOAT', 'DOUBLE'] },
    { category: 'String / Text', types: ['VARCHAR(255)', 'CHAR(1)', 'TEXT', 'MEDIUMTEXT', 'LONGTEXT', "ENUM('active','inactive')"] },
    { category: 'Date / Time', types: ['DATETIME', 'TIMESTAMP', 'DATE', 'TIME', 'YEAR'] },
    { category: 'Boolean', types: ['BOOLEAN', 'TINYINT(1)'] },
    { category: 'JSON & Binary', types: ['JSON', 'BLOB', 'LONGBLOB', 'VARBINARY(255)'] },
  ],
  sqlite: [
    { category: 'Core Storage Classes', types: ['INTEGER', 'TEXT', 'REAL', 'BLOB', 'NUMERIC'] },
    { category: 'Common Affinities', types: ['VARCHAR(255)', 'BOOLEAN', 'DATETIME', 'DOUBLE', 'DECIMAL(10,2)'] },
  ],
};

// ── Helper to resolve Parent (PK) vs Child (FK) ─────────────────────

function resolveFkRelationship(
  nodes: TableNode[],
  edge: Edge
): { parentNode: TableNode; parentCol: ColumnDef; childNode: TableNode; childCol: ColumnDef } | null {
  const nodeA = nodes.find((n) => n.id === edge.source);
  const nodeB = nodes.find((n) => n.id === edge.target);

  if (!nodeA || !nodeB) return null;

  const colA = nodeA.data.columns.find((c) => c.id === edge.sourceHandle);
  const colB = nodeB.data.columns.find((c) => c.id === edge.targetHandle);

  if (!colA || !colB) return null;

  // Determine parent (PK provider) vs child (FK owner)
  if (!colA.isPrimary && colB.isPrimary) {
    return { parentNode: nodeB, parentCol: colB, childNode: nodeA, childCol: colA };
  }

  return { parentNode: nodeA, parentCol: colA, childNode: nodeB, childCol: colB };
}

// ── SQL DDL Generation ─────────────────────────────────────────────

export function generateSql(
  nodes: TableNode[],
  edges: Edge[],
  dialect: SqlDialect = 'postgresql'
): Result<string> {
  try {
    let sql = `-- Generated by DevToolsPro SQL Schema Designer (${dialect.toUpperCase()})\n\n`;
    const q = dialect === 'mysql' ? '`' : '"';

    nodes.forEach((node) => {
      const { tableName, columns } = node.data;
      if (!tableName) return;

      sql += `CREATE TABLE ${q}${tableName}${q} (\n`;

      const colStrings: string[] = columns.map((col) => {
        const colName = col.name ? col.name.trim() : 'untitled';
        const colType = col.type ? col.type.trim() : 'VARCHAR(255)';

        let line = `  ${q}${colName}${q} ${colType}`;

        if (col.isPrimary) {
          if (dialect === 'sqlite' && colType.toUpperCase() === 'SERIAL') {
            line = `  ${q}${colName}${q} INTEGER PRIMARY KEY AUTOINCREMENT`;
          } else if (dialect === 'mysql' && colType.toUpperCase() === 'SERIAL') {
            line = `  ${q}${colName}${q} BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY`;
          } else {
            line += ' PRIMARY KEY';
          }
        }

        if (!col.isNullable && !col.isPrimary) {
          line += ' NOT NULL';
        }

        if (col.isUnique && !col.isPrimary) {
          line += ' UNIQUE';
        }

        if (col.defaultValue && col.defaultValue.trim()) {
          line += ` DEFAULT ${col.defaultValue.trim()}`;
        }

        return line;
      });

      // For SQLite, generate inline Foreign Keys inside CREATE TABLE
      if (dialect === 'sqlite') {
        edges.forEach((edge) => {
          const rel = resolveFkRelationship(nodes, edge);
          if (rel && rel.childNode.id === node.id) {
            colStrings.push(
              `  FOREIGN KEY (${q}${rel.childCol.name}${q}) REFERENCES ${q}${rel.parentNode.data.tableName}${q} (${q}${rel.parentCol.name}${q}) ON DELETE CASCADE`
            );
          }
        });
      }

      sql += colStrings.join(',\n');
      sql += '\n);\n\n';
    });

    // Foreign keys for PostgreSQL and MySQL
    if (edges.length > 0 && dialect !== 'sqlite') {
      let fkSql = '';
      edges.forEach((edge) => {
        const rel = resolveFkRelationship(nodes, edge);
        if (!rel) return;

        const fkName = `fk_${rel.childNode.data.tableName}_${rel.childCol.name}`;

        fkSql += `ALTER TABLE ${q}${rel.childNode.data.tableName}${q}\n`;
        fkSql += `  ADD CONSTRAINT ${q}${fkName}${q}\n`;
        fkSql += `  FOREIGN KEY (${q}${rel.childCol.name}${q})\n`;
        fkSql += `  REFERENCES ${q}${rel.parentNode.data.tableName}${q} (${q}${rel.parentCol.name}${q})\n`;
        fkSql += `  ON DELETE CASCADE ON UPDATE CASCADE;\n\n`;
      });

      if (fkSql) {
        sql += '-- Foreign Key Constraints\n' + fkSql;
      }
    }

    return { success: true, data: sql.trim() };
  } catch (error) {
    const msg = error instanceof Error ? error.message : 'Failed to generate SQL.';
    return { success: false, error: msg };
  }
}

// ── Prisma Schema Generation ───────────────────────────────────────

export function generatePrisma(nodes: TableNode[], edges: Edge[]): string {
  let prisma = `// Generated Prisma Schema\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\n`;

  const mapPrismaType = (type: string): string => {
    const t = type.toUpperCase();
    if (t.includes('INT') || t === 'SERIAL') return 'Int';
    if (t.includes('BIGINT')) return 'BigInt';
    if (t.includes('VARCHAR') || t.includes('TEXT') || t.includes('CHAR')) return 'String';
    if (t.includes('BOOL')) return 'Boolean';
    if (t.includes('TIME') || t.includes('DATE')) return 'DateTime';
    if (t.includes('UUID')) return 'String';
    if (t.includes('DECIMAL') || t.includes('FLOAT') || t.includes('DOUBLE')) return 'Float';
    if (t.includes('JSON')) return 'Json';
    return 'String';
  };

  nodes.forEach((node) => {
    const { tableName, columns } = node.data;
    const modelName = tableName.charAt(0).toUpperCase() + tableName.slice(1).replace(/_([a-z])/g, (_, c) => c.toUpperCase());

    prisma += `model ${modelName} {\n`;

    columns.forEach((col) => {
      let pType = mapPrismaType(col.type);
      if (col.isNullable && !col.isPrimary) pType += '?';

      const attributes: string[] = [];
      if (col.isPrimary) {
        attributes.push('@id');
        if (col.type.toUpperCase().includes('SERIAL') || col.type.toUpperCase().includes('INT')) {
          attributes.push('@default(autoincrement())');
        } else if (col.type.toUpperCase().includes('UUID')) {
          attributes.push('@default(uuid())');
        }
      }

      if (col.isUnique && !col.isPrimary) {
        attributes.push('@unique');
      }

      if (col.defaultValue && col.defaultValue.trim() && !attributes.some((a) => a.startsWith('@default'))) {
        attributes.push(`@default(${col.defaultValue.trim()})`);
      }

      prisma += `  ${col.name.padEnd(16)} ${pType.padEnd(12)} ${attributes.join(' ')}\n`;
    });

    // Relations
    edges.forEach((edge) => {
      const rel = resolveFkRelationship(nodes, edge);
      if (rel && rel.childNode.id === node.id) {
        const parentModel = rel.parentNode.data.tableName.charAt(0).toUpperCase() + rel.parentNode.data.tableName.slice(1).replace(/_([a-z])/g, (_, c) => c.toUpperCase());
        const relationField = rel.parentNode.data.tableName.toLowerCase();
        prisma += `  ${relationField.padEnd(16)} ${parentModel.padEnd(12)} @relation(fields: [${rel.childCol.name}], references: [${rel.parentCol.name}])\n`;
      }
    });

    prisma += `}\n\n`;
  });

  return prisma.trim();
}

// ── TypeScript Interfaces Generation ───────────────────────────────

export function generateTypeScript(nodes: TableNode[]): string {
  let ts = `// Generated TypeScript Interfaces\n\n`;

  const mapTsType = (type: string): string => {
    const t = type.toUpperCase();
    if (t.includes('INT') || t.includes('DECIMAL') || t.includes('FLOAT') || t.includes('DOUBLE') || t === 'SERIAL') return 'number';
    if (t.includes('VARCHAR') || t.includes('TEXT') || t.includes('CHAR') || t.includes('UUID')) return 'string';
    if (t.includes('BOOL')) return 'boolean';
    if (t.includes('TIME') || t.includes('DATE')) return 'Date | string';
    if (t.includes('JSON')) return 'Record<string, unknown>';
    return 'string';
  };

  nodes.forEach((node) => {
    const { tableName, columns } = node.data;
    const interfaceName = tableName.charAt(0).toUpperCase() + tableName.slice(1).replace(/_([a-z])/g, (_, c) => c.toUpperCase());

    ts += `export interface ${interfaceName} {\n`;
    columns.forEach((col) => {
      const optional = col.isNullable ? '?' : '';
      ts += `  ${col.name}${optional}: ${mapTsType(col.type)};\n`;
    });
    ts += `}\n\n`;
  });

  return ts.trim();
}

// ── Mermaid ER Diagram Generation ─────────────────────────────────

export function generateMermaid(nodes: TableNode[], edges: Edge[]): string {
  let m = `erDiagram\n`;

  nodes.forEach((node) => {
    const { tableName, columns } = node.data;
    m += `  ${tableName} {\n`;
    columns.forEach((col) => {
      const pk = col.isPrimary ? 'PK' : col.isUnique ? 'UK' : '';
      const typeStr = col.type.replace(/\s+/g, '_');
      m += `    ${typeStr} ${col.name} ${pk}\n`;
    });
    m += `  }\n`;
  });

  edges.forEach((edge) => {
    const rel = resolveFkRelationship(nodes, edge);
    if (rel) {
      m += `  ${rel.parentNode.data.tableName} ||--o{ ${rel.childNode.data.tableName} : "${rel.childCol.name}"\n`;
    }
  });

  return m.trim();
}

// ── Auto Layout Helper (Generous Gap between Tables) ───────────────

export function autoLayoutNodes(nodes: TableNode[]): TableNode[] {
  const columnsCount = Math.min(3, Math.ceil(Math.sqrt(nodes.length)));
  const nodeWidth = 500;
  const nodeHeight = 350;
  const spacingX = 220; // 220px horizontal gap between tables!
  const spacingY = 120; // 120px vertical gap between rows!

  return nodes.map((node, idx) => {
    const col = idx % columnsCount;
    const row = Math.floor(idx / columnsCount);
    return {
      ...node,
      position: {
        x: 60 + col * (nodeWidth + spacingX),
        y: 60 + row * (nodeHeight + spacingY),
      },
    };
  });
}

// ── SQL Parser (Import SQL DDL into Nodes) ─────────────────────────

export function parseSqlToNodes(
  sql: string,
  existingNodes: TableNode[] = []
): { nodes: TableNode[]; edges: Edge[] } {
  const nodes: TableNode[] = [];
  const edges: Edge[] = [];

  const cleanSql = sql.replace(/--.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  const statements = cleanSql.split(';').map((s) => s.trim()).filter(Boolean);

  let edgeCounter = 1;

  statements.forEach((stmt) => {
    const createMatch = stmt.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?['"`]?(\w+)['"`]?\s*\(([\s\S]+)\)/i);
    if (createMatch) {
      const tableName = createMatch[1];
      const body = createMatch[2];

      const columns: ColumnDef[] = [];
      const parts: string[] = [];
      let currentPart = '';
      let parenLevel = 0;

      for (let i = 0; i < body.length; i++) {
        const char = body[i];
        if (char === '(') parenLevel++;
        if (char === ')') parenLevel--;

        if (char === ',' && parenLevel === 0) {
          parts.push(currentPart.trim());
          currentPart = '';
        } else {
          currentPart += char;
        }
      }
      if (currentPart.trim()) parts.push(currentPart.trim());

      const existingNode = existingNodes.find((n) => n.data.tableName === tableName);
      const usedIds = new Set<string>();

      parts.forEach((part) => {
        const fkMatch = part.match(
          /FOREIGN\s+KEY\s*\(['"`]?(\w+)['"`]?\)\s*REFERENCES\s*['"`]?(\w+)['"`]?\s*\(['"`]?(\w+)['"`]?\)/i
        );
        if (fkMatch) {
          const sourceColName = fkMatch[1];
          const targetTableName = fkMatch[2];
          const targetColName = fkMatch[3];

          edges.push({
            id: `e-inline-${edgeCounter++}`,
            source: targetTableName,
            sourceHandle: targetColName,
            target: tableName,
            targetHandle: sourceColName,
            animated: true,
            type: 'smoothstep',
            label: `FK: ${sourceColName}`,
            style: { stroke: '#818cf8', strokeWidth: 2.5 },
          });
          return;
        }

        if (/^(?:PRIMARY\s+KEY|UNIQUE|CONSTRAINT|INDEX|KEY)\b/i.test(part)) {
          return;
        }

        const tokens = part.split(/\s+/);
        if (tokens.length >= 2) {
          const name = tokens[0].replace(/['"`]/g, '');
          const type = tokens[1].toUpperCase();
          const rest = tokens.slice(2).join(' ').toUpperCase();

          const isPrimary =
            rest.includes('PRIMARY KEY') ||
            type === 'SERIAL' ||
            rest.includes('AUTOINCREMENT') ||
            rest.includes('AUTO_INCREMENT');
          const isNullable = !rest.includes('NOT NULL');
          const isUnique = rest.includes('UNIQUE');

          let defaultValue = '';
          const defaultMatch = rest.match(/DEFAULT\s+([^\s,]+)/i);
          if (defaultMatch) {
            defaultValue = defaultMatch[1];
          }

          let colId = `col-${tableName}-${name}`;
          if (existingNode) {
            const matchedCol = existingNode.data.columns.find((c) => c.name === name && !usedIds.has(c.id));
            if (matchedCol) {
              colId = matchedCol.id;
            }
          }

          while (usedIds.has(colId)) {
            colId = `col-${tableName}-${name}-${Math.random().toString(36).substring(2, 7)}`;
          }
          usedIds.add(colId);

          columns.push({
            id: colId,
            name,
            type,
            isPrimary,
            isNullable,
            isUnique,
            defaultValue,
          });
        }
      });

      const position = existingNode
        ? existingNode.position
        : {
            x: (nodes.length % 2) * 720 + 60,
            y: Math.floor(nodes.length / 2) * 450 + 60,
          };

      nodes.push({
        id: `tbl-${tableName}`,
        type: 'tableNode',
        position,
        data: {
          tableName,
          columns,
        },
      });
    }

    const alterFkMatch = stmt.match(
      /ALTER\s+TABLE\s+['"`]?(\w+)['"`]?[\s\S]*?FOREIGN\s+KEY\s*\(['"`]?(\w+)['"`]?\)\s*REFERENCES\s*['"`]?(\w+)['"`]?\s*\(['"`]?(\w+)['"`]?\)/i
    );
    if (alterFkMatch) {
      const childTable = alterFkMatch[1];
      const childCol = alterFkMatch[2];
      const parentTable = alterFkMatch[3];
      const parentCol = alterFkMatch[4];

      edges.push({
        id: `e-alter-${edgeCounter++}`,
        source: parentTable,
        sourceHandle: parentCol,
        target: childTable,
        targetHandle: childCol,
        animated: true,
        type: 'smoothstep',
        label: `FK: ${childCol}`,
        style: { stroke: '#818cf8', strokeWidth: 2.5 },
      });
    }
  });

  const resolvedEdges: Edge[] = [];
  edges.forEach((edge) => {
    const parentNode = nodes.find((n) => n.data.tableName === edge.source);
    const childNode = nodes.find((n) => n.data.tableName === edge.target);

    if (parentNode && childNode) {
      const parentCol = parentNode.data.columns.find((c) => c.name === edge.sourceHandle);
      const childCol = childNode.data.columns.find((c) => c.name === edge.targetHandle);

      if (parentCol && childCol) {
        resolvedEdges.push({
          ...edge,
          source: parentNode.id,
          sourceHandle: parentCol.id,
          target: childNode.id,
          targetHandle: childCol.id,
        });
      }
    }
  });

  return { nodes, edges: resolvedEdges };
}

// ── Presets with Proper Spacing ─────────────────────────────────────

export const initialNodes: TableNode[] = [
  {
    id: 'tbl-users',
    type: 'tableNode',
    position: { x: 60, y: 60 },
    data: {
      tableName: 'users',
      columns: [
        { id: 'u1', name: 'id', type: 'SERIAL', isPrimary: true, isNullable: false },
        { id: 'u2', name: 'email', type: 'VARCHAR(255)', isPrimary: false, isNullable: false, isUnique: true },
        { id: 'u3', name: 'full_name', type: 'VARCHAR(100)', isPrimary: false, isNullable: true },
        { id: 'u4', name: 'created_at', type: 'TIMESTAMP', isPrimary: false, isNullable: false, defaultValue: 'CURRENT_TIMESTAMP' },
      ],
    },
  },
  {
    id: 'tbl-posts',
    type: 'tableNode',
    position: { x: 760, y: 60 },
    data: {
      tableName: 'posts',
      columns: [
        { id: 'p1', name: 'id', type: 'SERIAL', isPrimary: true, isNullable: false },
        { id: 'p2', name: 'user_id', type: 'INT', isPrimary: false, isNullable: false },
        { id: 'p3', name: 'title', type: 'VARCHAR(255)', isPrimary: false, isNullable: false },
        { id: 'p4', name: 'content', type: 'TEXT', isPrimary: false, isNullable: true },
        { id: 'p5', name: 'published', type: 'BOOLEAN', isPrimary: false, isNullable: false, defaultValue: 'false' },
      ],
    },
  },
];

export const initialEdges: Edge[] = [
  {
    id: 'e-users-posts',
    source: 'tbl-users',
    sourceHandle: 'u1',
    target: 'tbl-posts',
    targetHandle: 'p2',
    animated: true,
    type: 'smoothstep',
    label: 'FK: user_id ➔ id',
    style: { stroke: '#818cf8', strokeWidth: 2.5 },
  },
];

export const PRESET_TEMPLATES: Record<string, { nodes: TableNode[]; edges: Edge[] }> = {
  saasAuth: {
    nodes: [
      {
        id: 'tbl-users',
        type: 'tableNode',
        position: { x: 60, y: 60 },
        data: {
          tableName: 'users',
          columns: [
            { id: 'u1', name: 'id', type: 'UUID', isPrimary: true, isNullable: false, defaultValue: 'gen_random_uuid()' },
            { id: 'u2', name: 'email', type: 'VARCHAR(255)', isPrimary: false, isNullable: false, isUnique: true },
            { id: 'u3', name: 'password_hash', type: 'VARCHAR(255)', isPrimary: false, isNullable: false },
            { id: 'u4', name: 'role', type: 'VARCHAR(50)', isPrimary: false, isNullable: false, defaultValue: "'USER'" },
            { id: 'u5', name: 'created_at', type: 'TIMESTAMP', isPrimary: false, isNullable: false, defaultValue: 'CURRENT_TIMESTAMP' },
          ],
        },
      },
      {
        id: 'tbl-sessions',
        type: 'tableNode',
        position: { x: 760, y: 60 },
        data: {
          tableName: 'sessions',
          columns: [
            { id: 's1', name: 'id', type: 'UUID', isPrimary: true, isNullable: false },
            { id: 's2', name: 'user_id', type: 'UUID', isPrimary: false, isNullable: false },
            { id: 's3', name: 'token', type: 'VARCHAR(255)', isPrimary: false, isNullable: false, isUnique: true },
            { id: 's4', name: 'expires_at', type: 'TIMESTAMP', isPrimary: false, isNullable: false },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-user-session',
        source: 'tbl-users',
        sourceHandle: 'u1',
        target: 'tbl-sessions',
        targetHandle: 's2',
        animated: true,
        type: 'smoothstep',
        label: 'FK: user_id ➔ id',
        style: { stroke: '#818cf8', strokeWidth: 2.5 },
      },
    ],
  },
  ecommerce: {
    nodes: [
      {
        id: 'tbl-customers',
        type: 'tableNode',
        position: { x: 60, y: 60 },
        data: {
          tableName: 'customers',
          columns: [
            { id: 'c1', name: 'id', type: 'SERIAL', isPrimary: true, isNullable: false },
            { id: 'c2', name: 'email', type: 'VARCHAR(255)', isPrimary: false, isNullable: false, isUnique: true },
            { id: 'c3', name: 'phone', type: 'VARCHAR(50)', isPrimary: false, isNullable: true },
          ],
        },
      },
      {
        id: 'tbl-orders',
        type: 'tableNode',
        position: { x: 760, y: 60 },
        data: {
          tableName: 'orders',
          columns: [
            { id: 'o1', name: 'id', type: 'SERIAL', isPrimary: true, isNullable: false },
            { id: 'o2', name: 'customer_id', type: 'INT', isPrimary: false, isNullable: false },
            { id: 'o3', name: 'total_amount', type: 'DECIMAL(10,2)', isPrimary: false, isNullable: false },
            { id: 'o4', name: 'status', type: 'VARCHAR(50)', isPrimary: false, isNullable: false, defaultValue: "'PENDING'" },
          ],
        },
      },
      {
        id: 'tbl-products',
        type: 'tableNode',
        position: { x: 760, y: 480 },
        data: {
          tableName: 'products',
          columns: [
            { id: 'pr1', name: 'id', type: 'SERIAL', isPrimary: true, isNullable: false },
            { id: 'pr2', name: 'sku', type: 'VARCHAR(100)', isPrimary: false, isNullable: false, isUnique: true },
            { id: 'pr3', name: 'price', type: 'DECIMAL(10,2)', isPrimary: false, isNullable: false },
            { id: 'pr4', name: 'stock_quantity', type: 'INT', isPrimary: false, isNullable: false, defaultValue: '0' },
          ],
        },
      },
    ],
    edges: [
      {
        id: 'e-customer-orders',
        source: 'tbl-customers',
        sourceHandle: 'c1',
        target: 'tbl-orders',
        targetHandle: 'o2',
        animated: true,
        type: 'smoothstep',
        label: 'FK: customer_id ➔ id',
        style: { stroke: '#818cf8', strokeWidth: 2.5 },
      },
    ],
  },
};
